//Source code generated by AppGPT (www.appgpt.tech)

//Class to create tables and seed new database
import { DataSource } from 'typeorm';
import { DBConfiguration } from './Configuration';
import { SettingsEntity } from './db/Settings.entity';
//autogenerate imports based on resources
import { CarpenterEntity } from './db/Carpenter.entity';
import { DriverEntity } from './db/Driver.entity';
import { CleanerEntity } from './db/Cleaner.entity';
import { DeliveryBoyEntity } from './db/DeliveryBoy.entity';
import { ComputerOperatorEntity } from './db/ComputerOperator.entity';
import { MechanicEntity } from './db/Mechanic.entity';
import { TailorMasterEntity } from './db/TailorMaster.entity';
import { FruitSellerEntity } from './db/FruitSeller.entity';

export class Database {
  static dbConfiguration: DBConfiguration;
  public static ds: DataSource;

  static async Initialize(dbConfiguration: DBConfiguration) {
    Database.dbConfiguration = dbConfiguration;
    let dbConfig: any = dbConfiguration as any;
    //Autogenerate entities array from resource names

    dbConfig.entities = [
      SettingsEntity,
      CarpenterEntity,
      DriverEntity,
      CleanerEntity,
      DeliveryBoyEntity,
      ComputerOperatorEntity,
      MechanicEntity,
      TailorMasterEntity,
      FruitSellerEntity,
    ];
    Database.ds = new DataSource(dbConfig);
    await Database.ds.initialize();

    //TODO: Drop all tables

    await Database.Seed();
  }
  static async Seed() {
    let data: any = {
      Carpenter: [
        {
          Name: 'Name 1',
          Skills: 'Skills 1',
          Availability: 'Availability 1',
          ContactInformation: 'ContactInformation 1',
          Price: 0,
          id: 80,
        },
        {
          Name: 'Name 2',
          Skills: 'Skills 2',
          Availability: 'Availability 2',
          ContactInformation: 'ContactInformation 2',
          Price: 0.15,
          id: 12,
        },
        {
          Name: 'Name 3',
          Skills: 'Skills 3',
          Availability: 'Availability 3',
          ContactInformation: 'ContactInformation 3',
          Price: 0.91,
          id: 86,
        },
        {
          Name: 'Name 4',
          Skills: 'Skills 4',
          Availability: 'Availability 4',
          ContactInformation: 'ContactInformation 4',
          Price: 0.09,
          id: 83,
        },
        {
          Name: 'Name 5',
          Skills: 'Skills 5',
          Availability: 'Availability 5',
          ContactInformation: 'ContactInformation 5',
          Price: 0.22,
          id: 19,
        },
      ],
      Driver: [
        {
          Name: 'Name 1',
          Skills: 'Skills 1',
          Availability: 'Availability 1',
          ContactInformation: 'ContactInformation 1',
          Price: 0.79,
          id: 86,
        },
        {
          Name: 'Name 2',
          Skills: 'Skills 2',
          Availability: 'Availability 2',
          ContactInformation: 'ContactInformation 2',
          Price: 0.72,
          id: 53,
        },
        {
          Name: 'Name 3',
          Skills: 'Skills 3',
          Availability: 'Availability 3',
          ContactInformation: 'ContactInformation 3',
          Price: 0.45,
          id: 38,
        },
        {
          Name: 'Name 4',
          Skills: 'Skills 4',
          Availability: 'Availability 4',
          ContactInformation: 'ContactInformation 4',
          Price: 0.89,
          id: 58,
        },
        {
          Name: 'Name 5',
          Skills: 'Skills 5',
          Availability: 'Availability 5',
          ContactInformation: 'ContactInformation 5',
          Price: 0.33,
          id: 20,
        },
      ],
      Cleaner: [
        {
          Name: 'Name 1',
          Skills: 'Skills 1',
          Availability: 'Availability 1',
          ContactInformation: 'ContactInformation 1',
          Price: 0.21,
          id: 16,
        },
        {
          Name: 'Name 2',
          Skills: 'Skills 2',
          Availability: 'Availability 2',
          ContactInformation: 'ContactInformation 2',
          Price: 0.83,
          id: 1,
        },
        {
          Name: 'Name 3',
          Skills: 'Skills 3',
          Availability: 'Availability 3',
          ContactInformation: 'ContactInformation 3',
          Price: 0.11,
          id: 62,
        },
        {
          Name: 'Name 4',
          Skills: 'Skills 4',
          Availability: 'Availability 4',
          ContactInformation: 'ContactInformation 4',
          Price: 0.7,
          id: 30,
        },
        {
          Name: 'Name 5',
          Skills: 'Skills 5',
          Availability: 'Availability 5',
          ContactInformation: 'ContactInformation 5',
          Price: 0.92,
          id: 54,
        },
      ],
      DeliveryBoy: [
        {
          Name: 'Name 1',
          Skills: 'Skills 1',
          Availability: 'Availability 1',
          ContactInformation: 'ContactInformation 1',
          Price: 0.55,
          id: 43,
        },
        {
          Name: 'Name 2',
          Skills: 'Skills 2',
          Availability: 'Availability 2',
          ContactInformation: 'ContactInformation 2',
          Price: 0.8,
          id: 65,
        },
        {
          Name: 'Name 3',
          Skills: 'Skills 3',
          Availability: 'Availability 3',
          ContactInformation: 'ContactInformation 3',
          Price: 0.36,
          id: 4,
        },
        {
          Name: 'Name 4',
          Skills: 'Skills 4',
          Availability: 'Availability 4',
          ContactInformation: 'ContactInformation 4',
          Price: 0.42,
          id: 91,
        },
        {
          Name: 'Name 5',
          Skills: 'Skills 5',
          Availability: 'Availability 5',
          ContactInformation: 'ContactInformation 5',
          Price: 0.87,
          id: 55,
        },
      ],
      ComputerOperator: [
        {
          Name: 'Name 1',
          Skills: 'Skills 1',
          Availability: 'Availability 1',
          ContactInformation: 'ContactInformation 1',
          Price: 0.34,
          id: 38,
        },
        {
          Name: 'Name 2',
          Skills: 'Skills 2',
          Availability: 'Availability 2',
          ContactInformation: 'ContactInformation 2',
          Price: 0.73,
          id: 59,
        },
        {
          Name: 'Name 3',
          Skills: 'Skills 3',
          Availability: 'Availability 3',
          ContactInformation: 'ContactInformation 3',
          Price: 0.96,
          id: 100,
        },
        {
          Name: 'Name 4',
          Skills: 'Skills 4',
          Availability: 'Availability 4',
          ContactInformation: 'ContactInformation 4',
          Price: 0.29,
          id: 1,
        },
        {
          Name: 'Name 5',
          Skills: 'Skills 5',
          Availability: 'Availability 5',
          ContactInformation: 'ContactInformation 5',
          Price: 0.47,
          id: 48,
        },
      ],
      Mechanic: [
        {
          Name: 'Name 1',
          Skills: 'Skills 1',
          Availability: 'Availability 1',
          ContactInformation: 'ContactInformation 1',
          Price: 0.92,
          id: 44,
        },
        {
          Name: 'Name 2',
          Skills: 'Skills 2',
          Availability: 'Availability 2',
          ContactInformation: 'ContactInformation 2',
          Price: 0.48,
          id: 2,
        },
        {
          Name: 'Name 3',
          Skills: 'Skills 3',
          Availability: 'Availability 3',
          ContactInformation: 'ContactInformation 3',
          Price: 1,
          id: 58,
        },
        {
          Name: 'Name 4',
          Skills: 'Skills 4',
          Availability: 'Availability 4',
          ContactInformation: 'ContactInformation 4',
          Price: 0.33,
          id: 66,
        },
        {
          Name: 'Name 5',
          Skills: 'Skills 5',
          Availability: 'Availability 5',
          ContactInformation: 'ContactInformation 5',
          Price: 0.77,
          id: 6,
        },
      ],
      TailorMaster: [
        {
          Name: 'Name 1',
          Skills: 'Skills 1',
          Availability: 'Availability 1',
          ContactInformation: 'ContactInformation 1',
          Price: 0.42,
          id: 14,
        },
        {
          Name: 'Name 2',
          Skills: 'Skills 2',
          Availability: 'Availability 2',
          ContactInformation: 'ContactInformation 2',
          Price: 0.22,
          id: 86,
        },
        {
          Name: 'Name 3',
          Skills: 'Skills 3',
          Availability: 'Availability 3',
          ContactInformation: 'ContactInformation 3',
          Price: 0.02,
          id: 97,
        },
        {
          Name: 'Name 4',
          Skills: 'Skills 4',
          Availability: 'Availability 4',
          ContactInformation: 'ContactInformation 4',
          Price: 0.44,
          id: 94,
        },
        {
          Name: 'Name 5',
          Skills: 'Skills 5',
          Availability: 'Availability 5',
          ContactInformation: 'ContactInformation 5',
          Price: 0.81,
          id: 71,
        },
      ],
      FruitSeller: [
        {
          Name: 'Name 1',
          Skills: 'Skills 1',
          Availability: 'Availability 1',
          ContactInformation: 'ContactInformation 1',
          Price: 0.34,
          id: 37,
        },
        {
          Name: 'Name 2',
          Skills: 'Skills 2',
          Availability: 'Availability 2',
          ContactInformation: 'ContactInformation 2',
          Price: 0.43,
          id: 54,
        },
        {
          Name: 'Name 3',
          Skills: 'Skills 3',
          Availability: 'Availability 3',
          ContactInformation: 'ContactInformation 3',
          Price: 0.65,
          id: 58,
        },
        {
          Name: 'Name 4',
          Skills: 'Skills 4',
          Availability: 'Availability 4',
          ContactInformation: 'ContactInformation 4',
          Price: 0.26,
          id: 44,
        },
        {
          Name: 'Name 5',
          Skills: 'Skills 5',
          Availability: 'Availability 5',
          ContactInformation: 'ContactInformation 5',
          Price: 0.25,
          id: 61,
        },
      ],
    };
    //Autogenerate multiple such calls ie for each resource and its data object
    let isSeeded = await this.IsSeeded();
    //if (!isSeeded) {
    //forcing app recreation
    if (true) {
      console.log('   Seeding database...');
      await this.SeedResource('CarpenterEntity', data.Carpenter);
      await this.SeedResource('DriverEntity', data.Driver);
      await this.SeedResource('CleanerEntity', data.Cleaner);
      await this.SeedResource('DeliveryBoyEntity', data.DeliveryBoy);
      await this.SeedResource('ComputerOperatorEntity', data.ComputerOperator);
      await this.SeedResource('MechanicEntity', data.Mechanic);
      await this.SeedResource('TailorMasterEntity', data.TailorMaster);
      await this.SeedResource('FruitSellerEntity', data.FruitSeller);
      await this.SeedResource('SettingsEntity', {
        settingname: 'isSeeded',
        settingvalue: 'true',
      });
    } else {
      console.log('   Database seeded already!');
    }
  }
  static async IsSeeded() {
    const repo = Database.ds.getRepository('SettingsEntity');
    let rec: any = await repo.findOne({
      select: {
        settingname: true,
        settingvalue: true,
      },
      where: {
        settingname: 'isSeeded',
      },
    });
    if (rec && rec.settingvalue) return true;
    return false;
  }
  static async SeedResource(resourceName: any, resourceData: any) {
    const repo = Database.ds.getRepository(resourceName);
    //await repo.clear();
    console.log('   Seeding table ' + resourceName);
    await repo.upsert(resourceData, ['id']);
  }
}
