//Source code generated by AppGPT (www.appgpt.tech)
import { Admin, Resource, CustomRoutes } from 'react-admin';
import { customDataProvider } from './dataProvider';
import fakeDataProvider from 'ra-data-fakerest';
import { Dashboard } from './dashboard';
import { authProvider, apInitialize } from './authProvider';
import { i18nProvider } from './i18nProvider';
import LoginPage, { Login } from './Login';
import data from './data';
import {
  CarpenterList,
  CarpenterCreate,
  CarpenterEdit,
} from './resources/Carpenter';
import { DriverList, DriverCreate, DriverEdit } from './resources/Driver';
import { CleanerList, CleanerCreate, CleanerEdit } from './resources/Cleaner';
import {
  DeliveryBoyList,
  DeliveryBoyCreate,
  DeliveryBoyEdit,
} from './resources/DeliveryBoy';
import {
  ComputerOperatorList,
  ComputerOperatorCreate,
  ComputerOperatorEdit,
} from './resources/ComputerOperator';
import {
  MechanicList,
  MechanicCreate,
  MechanicEdit,
} from './resources/Mechanic';
import {
  TailorMasterList,
  TailorMasterCreate,
  TailorMasterEdit,
} from './resources/TailorMaster';
import {
  FruitSellerList,
  FruitSellerCreate,
  FruitSellerEdit,
} from './resources/FruitSeller';
import CarpenterIcon from '@mui/icons-material/Carpenter';
import DriverIcon from '@mui/icons-material/DriveEta';
import CleanerIcon from '@mui/icons-material/Clear';
import DeliveryBoyIcon from '@mui/icons-material/DeliveryDining';
import ComputerOperatorIcon from '@mui/icons-material/Computer';
import MechanicIcon from '@mui/icons-material/PriceChange';
import TailorMasterIcon from '@mui/icons-material/Mail';
import FruitSellerIcon from '@mui/icons-material/Sell';
// SUPERTOKENS
import React from 'react';
import SuperTokens, {
  SuperTokensWrapper,
  getSuperTokensRoutesForReactRouterDom,
} from 'supertokens-auth-react';
import ThirdPartyPasswordless from 'supertokens-auth-react/recipe/thirdpartypasswordless';
import Session from 'supertokens-auth-react/recipe/session';
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import * as reactRouterDom from 'react-router-dom';
let sessionFn = Session.init();
SuperTokens.init({
  appInfo: {
    appName: import.meta.env.VITE_SUPERTOKENS_APPNAME,
    apiDomain: import.meta.env.VITE_BACKEND_DOMAIN,
    websiteDomain: import.meta.env.VITE_SUPERTOKENS_WEBSITEDOMAIN,
    apiBasePath: import.meta.env.VITE_BACKEND_APIPATH + '/auth',
    websiteBasePath: import.meta.env.VITE_SUPERTOKENS_WEBSITEBASEPATH,
  },
  recipeList: [
    ThirdPartyPasswordless.init({
      contactMethod: 'EMAIL',
      signInUpFeature: {
        providers: [
          ThirdPartyPasswordless.Github.init(),
          //ThirdPartyPasswordless.Google.init(),
          //ThirdPartyPasswordless.Facebook.init(),
          //ThirdPartyPasswordless.Apple.init(),
        ],
      },
    }),
    sessionFn,
  ],
});
apInitialize(Session);
// END SUPERTOKENS
let dataProvider: any;
if (import.meta.env.VITE_USE_BACKEND_DATA === 'true') {
  dataProvider = customDataProvider(
    import.meta.env.VITE_BACKEND_DOMAIN +
      import.meta.env.VITE_BACKEND_APIPATH +
      '/proxy',
  );
} else {
  dataProvider = fakeDataProvider(data.defaultData);
}

const App = () => (
  <SuperTokensWrapper>
    <BrowserRouter basename="/a4a7c5723">
      <Admin
        authProvider={
          import.meta.env.VITE_ENVIRONMENT != 'DEV' ? authProvider : undefined
        }
        requireAuth
        loginPage={LoginPage}
        dataProvider={dataProvider}
        i18nProvider={i18nProvider}
        dashboard={Dashboard}
      >
        <Resource
          name="Carpenter"
          options={{ label: 'Carpenter' }}
          list={CarpenterList}
          create={CarpenterCreate}
          edit={CarpenterEdit}
          recordRepresentation="Name"
          icon={CarpenterIcon}
        />
        <Resource
          name="Driver"
          options={{ label: 'Driver' }}
          list={DriverList}
          create={DriverCreate}
          edit={DriverEdit}
          recordRepresentation="Name"
          icon={DriverIcon}
        />
        <Resource
          name="Cleaner"
          options={{ label: 'Cleaner' }}
          list={CleanerList}
          create={CleanerCreate}
          edit={CleanerEdit}
          recordRepresentation="Name"
          icon={CleanerIcon}
        />
        <Resource
          name="DeliveryBoy"
          options={{ label: 'Delivery Boy' }}
          list={DeliveryBoyList}
          create={DeliveryBoyCreate}
          edit={DeliveryBoyEdit}
          recordRepresentation="Name"
          icon={DeliveryBoyIcon}
        />
        <Resource
          name="ComputerOperator"
          options={{ label: 'Computer Operator' }}
          list={ComputerOperatorList}
          create={ComputerOperatorCreate}
          edit={ComputerOperatorEdit}
          recordRepresentation="Name"
          icon={ComputerOperatorIcon}
        />
        <Resource
          name="Mechanic"
          options={{ label: 'Mechanic' }}
          list={MechanicList}
          create={MechanicCreate}
          edit={MechanicEdit}
          recordRepresentation="Name"
          icon={MechanicIcon}
        />
        <Resource
          name="TailorMaster"
          options={{ label: 'Tailor Master' }}
          list={TailorMasterList}
          create={TailorMasterCreate}
          edit={TailorMasterEdit}
          recordRepresentation="Name"
          icon={TailorMasterIcon}
        />
        <Resource
          name="FruitSeller"
          options={{ label: 'Fruit Seller' }}
          list={FruitSellerList}
          create={FruitSellerCreate}
          edit={FruitSellerEdit}
          recordRepresentation="Name"
          icon={FruitSellerIcon}
        />
        <CustomRoutes noLayout>
          {/*This renders the login UI on the /auth route*/}
          {getSuperTokensRoutesForReactRouterDom(reactRouterDom)}
          {/*Your app routes*/}
        </CustomRoutes>
      </Admin>
    </BrowserRouter>
  </SuperTokensWrapper>
);

export default App;
