//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    Carpenter: {
      name: 'Carpenter',
      fields: {
        Name: 'Name',
        Skills: 'Skills',
        Availability: 'Availability',
        ContactInformation: 'Contact Information',
        Price: 'Price',
        id: 'id',
      },
    },
    Driver: {
      name: 'Driver',
      fields: {
        Name: 'Name',
        Skills: 'Skills',
        Availability: 'Availability',
        ContactInformation: 'Contact Information',
        Price: 'Price',
        id: 'id',
      },
    },
    Cleaner: {
      name: 'Cleaner',
      fields: {
        Name: 'Name',
        Skills: 'Skills',
        Availability: 'Availability',
        ContactInformation: 'Contact Information',
        Price: 'Price',
        id: 'id',
      },
    },
    DeliveryBoy: {
      name: 'Delivery Boy',
      fields: {
        Name: 'Name',
        Skills: 'Skills',
        Availability: 'Availability',
        ContactInformation: 'Contact Information',
        Price: 'Price',
        id: 'id',
      },
    },
    ComputerOperator: {
      name: 'Computer Operator',
      fields: {
        Name: 'Name',
        Skills: 'Skills',
        Availability: 'Availability',
        ContactInformation: 'Contact Information',
        Price: 'Price',
        id: 'id',
      },
    },
    Mechanic: {
      name: 'Mechanic',
      fields: {
        Name: 'Name',
        Skills: 'Skills',
        Availability: 'Availability',
        ContactInformation: 'Contact Information',
        Price: 'Price',
        id: 'id',
      },
    },
    TailorMaster: {
      name: 'Tailor Master',
      fields: {
        Name: 'Name',
        Skills: 'Skills',
        Availability: 'Availability',
        ContactInformation: 'Contact Information',
        Price: 'Price',
        id: 'id',
      },
    },
    FruitSeller: {
      name: 'Fruit Seller',
      fields: {
        Name: 'Name',
        Skills: 'Skills',
        Availability: 'Availability',
        ContactInformation: 'Contact Information',
        Price: 'Price',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    Carpenter: {
      name: 'Carpenter (fr)',
      fields: {
        Name: 'Name (fr)',
        Skills: 'Skills (fr)',
        Availability: 'Availability (fr)',
        ContactInformation: 'Contact Information (fr)',
        Price: 'Price (fr)',
        id: 'id',
      },
    },
    Driver: {
      name: 'Driver (fr)',
      fields: {
        Name: 'Name (fr)',
        Skills: 'Skills (fr)',
        Availability: 'Availability (fr)',
        ContactInformation: 'Contact Information (fr)',
        Price: 'Price (fr)',
        id: 'id',
      },
    },
    Cleaner: {
      name: 'Cleaner (fr)',
      fields: {
        Name: 'Name (fr)',
        Skills: 'Skills (fr)',
        Availability: 'Availability (fr)',
        ContactInformation: 'Contact Information (fr)',
        Price: 'Price (fr)',
        id: 'id',
      },
    },
    DeliveryBoy: {
      name: 'Delivery Boy (fr)',
      fields: {
        Name: 'Name (fr)',
        Skills: 'Skills (fr)',
        Availability: 'Availability (fr)',
        ContactInformation: 'Contact Information (fr)',
        Price: 'Price (fr)',
        id: 'id',
      },
    },
    ComputerOperator: {
      name: 'Computer Operator (fr)',
      fields: {
        Name: 'Name (fr)',
        Skills: 'Skills (fr)',
        Availability: 'Availability (fr)',
        ContactInformation: 'Contact Information (fr)',
        Price: 'Price (fr)',
        id: 'id',
      },
    },
    Mechanic: {
      name: 'Mechanic (fr)',
      fields: {
        Name: 'Name (fr)',
        Skills: 'Skills (fr)',
        Availability: 'Availability (fr)',
        ContactInformation: 'Contact Information (fr)',
        Price: 'Price (fr)',
        id: 'id',
      },
    },
    TailorMaster: {
      name: 'Tailor Master (fr)',
      fields: {
        Name: 'Name (fr)',
        Skills: 'Skills (fr)',
        Availability: 'Availability (fr)',
        ContactInformation: 'Contact Information (fr)',
        Price: 'Price (fr)',
        id: 'id',
      },
    },
    FruitSeller: {
      name: 'Fruit Seller (fr)',
      fields: {
        Name: 'Name (fr)',
        Skills: 'Skills (fr)',
        Availability: 'Availability (fr)',
        ContactInformation: 'Contact Information (fr)',
        Price: 'Price (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
